apiVersion: apps/v1
kind: Deployment
metadata:
  name: clumsybirddeployment
  labels:
    app: clumsybird
    tier: frontend
spec:
  selector: 
    matchLabels:
      app: clumsybird
      tier: frontend
  replicas: 2 
  template:
    metadata:
      labels: 
        app: clumsybird
        tier: frontend
    spec:
      containers:
      - image: ghcr.io/metalstormbass/clumsybird/clumsybird@sha256:f4e89ecb8739c92f863fa263e799625d3bd32b77eb69f84904c95edb70434de5
        imagePullPolicy: Always
        name: clumsybird
        ports:
        - containerPort: 8001
          
---
apiVersion: v1
kind: Service
metadata:
  name: clumsybirdservice
  labels:
    app: clumsybird
spec: 
  ports:
   - port: 80
     targetPort: 8001
  selector:
    app: clumsybird
    tier: frontend
  type: LoadBalancer
